Lh 360 creating a calendar
travelmakers/travelmakers-design-v2 pull request #19
Opened 2023-04-26 01:45 UTC by sgd122

LH-360

## 수정한 내용
  
- [X] 캘린더 컴포넌트 개발

## 추가적으로 알리고 싶은 내용
  
- `useCalendar`를 이용하여 1달 단위로의 달력을 표출시킬 수 있다.
- **calendar**
  - type이 'tour(투어)' 일 경우 일자는 범위 선택이 아니라 하나의 일자에 대해서만 선택이 가능하다.
  - type이 'move-in(입주)' 일 경우 범위(from~to)형태로 일자를 선택한다.
  - selectableDates에 선택 가능한 일자를 넣어야만 정상적으로 일자에 대한 선택이 가능하다.
  - minNight로 최소 선택가능 범위를 작성해주어야한다.
  - maxNight로 최대 선택가능 범위를 작성해주어야한다.
  - onChange함수를 통해 선택한 일자에 대해서 확인할 수 있다.

2023-04-26 11:01 UTC, baegofda requested changes
캘린더가 많은 케이스가 있다보니 좀 비대해진 느낌이있는데 전체적으로 리팩토링이 필요할 듯 하여 같이 보면서 얘기를 나누고 리팩토링하는게 좋을 것 같습니다. 일단 남길 수 있는 부분은 남겼고 얘기를 나눠보면 좋을 것 같아요!

2023-04-27 01:28 UTC, baegofda commented on packages/travelmakers-design-core/src/components/Calendar/_components/TableHead/index.tsx
> +const DAYS = ["일", "월", "화", "수", "목", "금", "토"];
P2; 사용되지 않는 것 같아서 지워도 될 것 같습니다!

2023-04-27 04:35 UTC, sgd122 commented on packages/travelmakers-design-core/src/components/Calendar/_components/TableHead/index.tsx
> +const DAYS = ["일", "월", "화", "수", "목", "금", "토"];
✅

2023-04-27 04:35 UTC, sgd122 commented on packages/travelmakers-design-core/src/components/Calendar/_components/DateCell/DateCell.tsx
> +        onClick={() => visible && onClick(day)}
✅

2023-04-27 04:41 UTC, baegofda requested changes

2023-04-27 04:41 UTC, baegofda commented on packages/travelmakers-design-core/src/components/Calendar/Calendar.tsx
> +    };
P3; 유틸 성향이 강한 boolean 함수들은 if문을 제거하는게 어떨까요? 오히려 복잡한 느낌입니다.

```suggestion
    const isBetweenNotSelectedDays = (day: DateCellDay) => {
     return (
        checked.from &&
        !checked.to &&
        differenceInDays(day.date, checked.from.date) > 0 &&
        differenceInDays(enabledDays, day.date) >= 0
     )
    };
```

2023-04-27 04:41 UTC, baegofda commented on packages/travelmakers-design-core/src/components/Calendar/Calendar.tsx
> +      }
P3; 해당 함수 내의 for문들의 경우엔 선언형으로 some을 이용해보는게 어떨까요?

```suggestion
      disabledDays.some((disabledDay) => isEqual(disabledDay, day.date))
```

2023-04-27 04:41 UTC, baegofda commented on packages/travelmakers-design-core/src/components/Calendar/Calendar.tsx
> +          }
P3; 이부분도 중첩을 조금 줄이기 위해 삼항 연산자로 하는건 어떨까요?

```suggestion
          differenceInDays(enabledDays, day.date) > 0 ? "disabled-between" : "disabled-to-between"
```

2023-04-27 04:53 UTC, sgd122 commented on packages/travelmakers-design-core/src/components/Calendar/Calendar.tsx
> +      }
✅

2023-04-27 04:57 UTC, sgd122 commented on packages/travelmakers-design-core/src/components/Calendar/Calendar.tsx
> +          }
✅

2023-04-27 05:00 UTC, sgd122 commented on packages/travelmakers-design-core/src/components/Calendar/Calendar.tsx
> +    };
✅

2023-04-27 06:02 UTC, sgd122 commented on packages/travelmakers-design-core/src/components/Calendar/_components/HeadTitle/index.tsx
> +          <td key={day} className={classes.tableCell}>
✅

2023-04-27 06:49 UTC, sgd122 commented on packages/travelmakers-design-core/src/components/Calendar/_components/DateCell/DateCell.type.ts
> +export type DateCellComponent = <C extends React.ElementType = "div">(
✅

2023-04-27 06:49 UTC, sgd122 commented on packages/travelmakers-design-core/src/components/Calendar/Calendar.tsx
> +              {state.weeks.map((week, index) => (
✅

2023-04-27 06:49 UTC, sgd122 commented on packages/travelmakers-design-core/src/components/Calendar/Calendar.tsx
> +                  <tr key={index}>
✅

2023-04-27 07:01 UTC, merged